-- Night light (hyprsunset) — Lua source of truth.
--
-- hyprsunset is a separate daemon that only reads hyprsunset.conf
-- (time-based profiles). This file defines the profiles in Lua, writes
-- the equivalent hyprsunset.conf at start, and launches hyprsunset.

local profiles = {
  { time = "07:00", identity = true },
  { time = "18:00", temperature = 2500, gamma = 0.8 },
}

local function write_conf()
  local lines = {
    "# Generated by hyprsunset.lua — edit the Lua profiles, not this file.",
  }
  for _, p in ipairs(profiles) do
    lines[#lines + 1] = "profile {"
    lines[#lines + 1] = "    time = " .. p.time
    if p.identity then
      lines[#lines + 1] = "    identity = true"
    end
    if p.temperature then
      lines[#lines + 1] = "    temperature = " .. p.temperature
    end
    if p.gamma then
      lines[#lines + 1] = "    gamma = " .. p.gamma
    end
    lines[#lines + 1] = "}"
  end
  return table.concat(lines, "\n")
end

hl.on("hyprland.start", function()
  local conf_path = (os.getenv("HOME") or "") .. "/.config/hypr/hyprsunset.conf"
  local file = io.open(conf_path, "w")
  if file then
    file:write(write_conf())
    file:close()
  end
  hl.exec_cmd("pkill -x hyprsunset; setsid uwsm-app -- hyprsunset >/dev/null 2>&1 &")
end)